#!/usr/bin/env python

Import('env')


common_x11 = [
    "crash_handler_x11.cpp",
    "os_x11.cpp",
    "key_mapping_x11.cpp",
    "joystick_linux.cpp",
]

if (env['use_egles2'] == 'yes'):
    common_x11.append("context_gl_x11_egl.cpp")
else:
    common_x11.append("context_gl_x11_glx.cpp")

prog = env.add_program('#bin/godot', ['godot_x11.cpp'] + common_x11)
