#!/usr/bin/env python

Import('env')


common_x11 = [
    "godot_x11.cpp",
    "crash_handler_x11.cpp",
    "os_x11.cpp",
    "key_mapping_x11.cpp",
    "joystick_linux.cpp",
]

if (env['use_egles2'] == 'yes'):
    common_x11.append("context_gl_x11_egl.cpp")
else:
    common_x11.append("context_gl_x11_glx.cpp")

if (env['buildlib'] == 'yes'):
    lib = env.add_shared_library('#bin/libgodot', common_x11)
else:
    prog_env = env.Clone()
    if (env['extmain'] == 'no'):
        prog_env.Append(CPPFLAGS=['-DIMPLEMENT_MAIN'])
    prog_env = prog_env.add_program('#bin/godot', common_x11)
